#!/usr/bin/env python3
"""Generate the Halmos form of the Kontrol list-invariant proofs.

src/test/kontrol/ proves RepoTokenList and TermAuctionList invariants with Kontrol. Halmos can prove
the same properties with the same cheatcodes (halmos/kontrol-shim/ maps them onto Halmos) once two
things change, and this script makes exactly those changes, in generated copies:

1. Each list is built by `while (kevm.freshBool() != 0)`, which Kontrol bounds with kontrol.toml's
   `bmc-depth`. Halmos does not bound that loop, so the copy caps it at that same bmc-depth, read
   from kontrol.toml, so the lists considered are the ones Kontrol considers.
2. Kontrol builds the list in `setUp`, but halmos requires a single-path `setUp` and building a list
   of symbolic length branches. The copy builds it at the start of each test instead.

The Kontrol files are not modified. Every change is checked against an exact count, and each suite's
test functions must be exactly the ones kontrol.toml's `match-test` lists, so a change to the Kontrol
sources or configuration that this script does not understand stops generation instead of producing
a proof of something else. Output goes to halmos/generated/, outside src/ so that no default-profile
forge command picks it up, and is not committed.

Usage: scripts/halmos-from-kontrol.py
"""

import pathlib
import re
import sys

KONTROL = pathlib.Path("src/test/kontrol")
KONTROL_CONFIG = pathlib.Path("kontrol.toml")
OUT_DIR = pathlib.Path("halmos/generated")

# Base test contracts whose list-building loop is bounded.
BASES = ["RepoTokenListTest", "TermAuctionListTest"]

# invariants contract, the bases it inherits, the Kontrol files it imports that have generated copies,
# and the initializer its setUp calls.
SUITES = [
    ("RepoTokenListInvariantsTest", ["RepoTokenListTest"], ["RepoTokenListTest.t.sol"],
     "_initializeRepoTokenList"),
    ("TermAuctionListInvariantsTest", ["RepoTokenListTest", "TermAuctionListTest"],
     ["RepoTokenListInvariants.t.sol", "TermAuctionListTest.t.sol"], "_initializeTermAuctionList"),
]
HEADER = "// Generated by scripts/halmos-from-kontrol.py from src/test/kontrol/{name}. Do not edit or commit.\n"


def fail(message):
    sys.exit(f"halmos-from-kontrol: {message}")


def kontrol_config():
    """The bmc-depth kontrol.toml sets, and the tests each proof contract is configured with."""
    text = KONTROL_CONFIG.read_text()
    depths = {int(d) for d in re.findall(r"^\s*bmc-depth\s*=\s*(\d+)", text, re.M)}
    if len(depths) != 1:
        fail(f"kontrol.toml must set bmc-depth, and every bmc-depth in it must have the same value; "
             f"found {sorted(depths) or 'none'}")
    configured = {}
    for contract, test in re.findall(r'"(\w+)\.(test\w+)"', text):
        configured.setdefault(contract, set()).add(test)
    return depths.pop(), configured


def replace_exactly(text, old, new, count, what):
    found = text.count(old)
    if found != count:
        fail(f"{what}: expected {count} occurrence(s) of {old!r}, found {found}")
    return text.replace(old, new)


def generate_base(base, max_nodes):
    name = f"{base}.t.sol"
    text = (KONTROL / name).read_text()
    text = replace_exactly(
        text,
        "while (kevm.freshBool() != 0) {",
        f"for (uint256 halmosNodes = 0; halmosNodes < {max_nodes} && kevm.freshBool() != 0; halmosNodes++) {{",
        1,
        f"{name} list-building loop",
    )
    text, renamed = re.subn(rf"\bcontract {base}\b", f"contract Halmos{base}", text)
    if renamed != 1:
        fail(f"{name}: expected one `contract {base}`, found {renamed}")
    (OUT_DIR / name).write_text(HEADER.format(name=name) + text)


def generate_invariants(invariants, bases, imports, initializer, configured):
    name = f"{invariants[:-len('Test')]}.t.sol"
    text = (KONTROL / name).read_text()

    setup = re.search(r"function setUp\(\) public \{(.*?)\n    \}", text, re.S)
    if not setup:
        fail(f"{name}: no setUp()")
    body = setup.group(1)
    call = re.search(rf"\n(\s*//[^\n]*\n)?\s*{initializer}\(\);", body)
    if not call or body.count(f"{initializer}();") != 1:
        fail(f"{name}: setUp() must call {initializer}() exactly once")
    text = text[: setup.start(1)] + body[: call.start()] + body[call.end():] + text[setup.end(1):]

    def build_first(match):
        return (match.group(0)
                + "\n        // halmos requires a single-path setUp, so each proof builds its own bounded list."
                + f"\n        {initializer}();")

    declared = set(re.findall(r"function (test\w+)\(", text))
    if declared != configured:
        fail(f"{name}: test functions {sorted(declared)} are not the ones kontrol.toml configures for "
             f"{invariants}: {sorted(configured)}")
    text, found = re.subn(r"function test\w+\([^)]*\)\s*external\s*\{", build_first, text)
    if found != len(configured):
        fail(f"{name}: expected {len(configured)} external test functions, found {found}")

    for imported in imports:
        text = replace_exactly(
            text,
            f'import "src/test/kontrol/{imported}";',
            f'import "{OUT_DIR}/{imported}";',
            1,
            f"{name} import of {imported}",
        )

    header = re.search(rf"\bcontract {invariants} is\s+([^{{]+)\{{", text)
    if not header:
        fail(f"{name}: no `contract {invariants} is ... {{` declaration")
    inherited = [b.strip() for b in header.group(1).split(",")]
    if inherited != bases:
        fail(f"{name}: expected {invariants} to inherit {bases}, found {inherited}")
    renamed = f"contract Halmos{invariants} is " + ", ".join(f"Halmos{b}" for b in bases) + " {"
    text = text[: header.start()] + renamed + text[header.end():]
    (OUT_DIR / name).write_text(HEADER.format(name=name) + text)
    return len(configured)


def main():
    if len(sys.argv) > 1:
        fail("takes no arguments: output always goes to halmos/generated/")
    max_nodes, configured = kontrol_config()
    unported = sorted(set(configured) - {invariants for invariants, _, _, _ in SUITES})
    if unported:
        fail(f"kontrol.toml configures tests for {unported}, which have no Halmos form: add them to SUITES")
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for base in BASES:
        generate_base(base, max_nodes)
    for invariants, bases, imports, initializer in SUITES:
        if invariants not in configured:
            fail(f"kontrol.toml configures no tests for {invariants}")
        tests = generate_invariants(invariants, bases, imports, initializer, configured[invariants])
        print(f"Halmos{invariants}: {tests} proofs, lists of at most {max_nodes} nodes (kontrol.toml bmc-depth)")


if __name__ == "__main__":
    main()
