#!/usr/bin/env python3
"""Generate the Halmos form of the Kontrol list-invariant proofs.

src/test/kontrol/ proves RepoTokenList and TermAuctionList invariants with Kontrol. Halmos can prove
the same properties with the same cheatcodes (halmos/kontrol-shim/ maps them onto Halmos) once two
things change, and this script makes exactly those changes, in generated copies:

1. Each list is built by `while (kevm.freshBool() != 0)`, which Kontrol bounds with kontrol.toml's
   `bmc-depth`. Halmos does not bound that loop, so the copy caps it at MAX_NODES iterations. With
   MAX_NODES equal to the Kontrol bmc-depth, the lists considered are the ones Kontrol considers.
2. Kontrol builds the list in `setUp`, but halmos requires a single-path `setUp` and building a list
   of symbolic length branches. The copy builds it at the start of each test instead.

The Kontrol files are not modified. Every change is checked against an exact count, so a change to
the Kontrol sources that this script does not understand stops generation instead of producing a
proof of something else. Output goes to src/test/halmos-generated/, which is not committed.

Usage: scripts/halmos-from-kontrol.py [output-dir]
"""

import pathlib
import re
import sys

KONTROL = pathlib.Path("src/test/kontrol")
MAX_NODES = 2  # kontrol.toml: bmc-depth = 2

# Base test contracts whose list-building loop is bounded.
BASES = ["RepoTokenListTest", "TermAuctionListTest"]

# invariants contract, the bases it inherits, the Kontrol files it imports that have generated copies,
# the initializer its setUp calls, and its number of test functions (as listed in kontrol.toml).
SUITES = [
    ("RepoTokenListInvariantsTest", ["RepoTokenListTest"], ["RepoTokenListTest.t.sol"],
     "_initializeRepoTokenList", 7),
    ("TermAuctionListInvariantsTest", ["RepoTokenListTest", "TermAuctionListTest"],
     ["RepoTokenListInvariants.t.sol", "TermAuctionListTest.t.sol"], "_initializeTermAuctionList", 9),
]
HEADER = "// Generated by scripts/halmos-from-kontrol.py from src/test/kontrol/{name}. Do not edit or commit.\n"


def fail(message):
    sys.exit(f"halmos-from-kontrol: {message}")


def replace_exactly(text, old, new, count, what):
    found = text.count(old)
    if found != count:
        fail(f"{what}: expected {count} occurrence(s) of {old!r}, found {found}")
    return text.replace(old, new)


def generate_base(base, out_dir):
    name = f"{base}.t.sol"
    text = (KONTROL / name).read_text()
    text = replace_exactly(
        text,
        "while (kevm.freshBool() != 0) {",
        f"for (uint256 halmosNodes = 0; halmosNodes < {MAX_NODES} && kevm.freshBool() != 0; halmosNodes++) {{",
        1,
        f"{name} list-building loop",
    )
    text, renamed = re.subn(rf"\bcontract {base}\b", f"contract Halmos{base}", text)
    if renamed != 1:
        fail(f"{name}: expected one `contract {base}`, found {renamed}")
    (out_dir / name).write_text(HEADER.format(name=name) + text)


def generate_invariants(invariants, bases, imports, initializer, tests, out_dir):
    name = f"{invariants[:-len('Test')]}.t.sol"
    text = (KONTROL / name).read_text()

    setup = re.search(r"function setUp\(\) public \{(.*?)\n    \}", text, re.S)
    if not setup:
        fail(f"{name}: no setUp()")
    body = setup.group(1)
    call = re.search(rf"\n(\s*//[^\n]*\n)?\s*{initializer}\(\);", body)
    if not call or body.count(f"{initializer}();") != 1:
        fail(f"{name}: setUp() must call {initializer}() exactly once")
    text = text[: setup.start(1)] + body[: call.start()] + body[call.end():] + text[setup.end(1):]

    def build_first(match):
        return (match.group(0)
                + "\n        // halmos requires a single-path setUp, so each proof builds its own bounded list."
                + f"\n        {initializer}();")

    text, found = re.subn(r"function test\w+\([^)]*\)\s*external\s*\{", build_first, text)
    if found != tests:
        fail(f"{name}: expected {tests} test functions, found {found}")

    for imported in imports:
        text = replace_exactly(
            text,
            f'import "src/test/kontrol/{imported}";',
            f'import "src/test/halmos-generated/{imported}";',
            1,
            f"{name} import of {imported}",
        )

    header = re.search(rf"\bcontract {invariants} is\s+([^{{]+)\{{", text)
    if not header:
        fail(f"{name}: no `contract {invariants} is ... {{` declaration")
    inherited = [b.strip() for b in header.group(1).split(",")]
    if inherited != bases:
        fail(f"{name}: expected {invariants} to inherit {bases}, found {inherited}")
    renamed = f"contract Halmos{invariants} is " + ", ".join(f"Halmos{b}" for b in bases) + " {"
    text = text[: header.start()] + renamed + text[header.end():]
    (out_dir / name).write_text(HEADER.format(name=name) + text)


def main():
    out_dir = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "src/test/halmos-generated")
    out_dir.mkdir(parents=True, exist_ok=True)
    for base in BASES:
        generate_base(base, out_dir)
    for invariants, bases, imports, initializer, tests in SUITES:
        generate_invariants(invariants, bases, imports, initializer, tests, out_dir)
        print(f"Halmos{invariants}: {tests} proofs, lists of at most {MAX_NODES} nodes built in each proof")


if __name__ == "__main__":
    main()
