name: "[mainnet-deploy] deploy vaults keeper helper"
on:
  workflow_dispatch:
    inputs:
      devopsAddress:
        description: 'Devops address'
        required: true
        default: '0x'
      initialKeeper:
        description: 'Initial keeper address'
        required: true
        default: '0x'
      implOnly:
        description: 'Impl only'
        required: false
        default: 'false'
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: mainnet
      url: https://term-finance.github.io/yearn-v3-term-vault/
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
      - run: forge install
      - run: forge build
      - run: forge tree
      - name: Run deploy script
        run: forge script script/TermVaultsKeeper.s.sol:TermVaultsKeeperDeployer --rpc-url $RPC_URL --verify --broadcast --verbosity 4
        env:
          RPC_URL:  ${{ secrets.RPC_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          DEVOPS_ADDRESS: ${{ github.event.inputs.devopsAddress }}
          INITIAL_KEEPER_ADDRESS: ${{ github.event.inputs.initialKeeper }}
          IMPL_ONLY: ${{ github.event.inputs.implOnly }}