name: "[sepolia-deploy] deploy strategy (hardhat)"
on:
  workflow_dispatch:
    inputs:
      asset:
        description: 'Asset address'
        required: true
        default: '0x'
      strategyMeta:
        description: 'Yearn strategy name and token symbol separated by a comma'
        required: true
        default: 'SomeName,SOMESYMBOL'
      strategyManagementAddress:
        description: 'Strategy management address'
        required: true
        default: '0x'
      feeRecipient:
        description: 'FeeRecipient address'
        required: false
        default: '0x'
      timeToMaturityThreshold:
        description: 'Time to maturity threshold'
        required: false
        default: '0'
      repoTokenConcentrationLimit:
        description: 'Repo token concentration limit'
        required: false
        default: '0.01'
      requiredReserveRatio:
        description: 'Required reserve ratio'
        required: false
        default: '0.01'
      collateralTokens:
        description: 'Collateral tokens comma separated'
        required: false
        default: '0x'
      minCollateralRatios:
        description: 'Minimum collateral ratio comma separated'
        required: false
        default: '0.01'
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: sepolia
      url: https://term-finance.github.io/yearn-v3-term-vault/
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: foundry-rs/foundry-toolchain@v1
      - run: forge install
      - run: forge remappings > remappings.txt
      - id: nodeversion
        run: echo "version=$(grep nodejs .tool-versions | sed -e 's/[^[:space:]]*[[:space:]]*//')" >> $GITHUB_OUTPUT
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nodeversion.outputs.version }}
          cache: yarn
      - run: yarn install
      - run: rm -rf src/test/kontrol/
      - run: yarn sepolia:deploy-strategy
        env:
          ASSET_ADDRESS: ${{ github.event.inputs.asset }}
          YEARN_VAULT_ADDRESS: ${{ vars.YEARN_VAULT_ADDRESS }}
          DISCOUNT_RATE_ADAPTER_ADDRESS: ${{ vars.DISCOUNT_RATE_ADAPTER_ADDRESS }}
          TERM_CONTROLLER_ADDRESS: ${{ vars.TERM_CONTROLLER_ADDRESS }}
          DISCOUNT_RATE_MARKUP: ${{ vars.DISCOUNT_RATE_MARKUP }}
          TIME_TO_MATURITY_THRESHOLD: ${{ github.event.inputs.timeToMaturityThreshold }}
          REPOTOKEN_CONCENTRATION_LIMIT: ${{ github.event.inputs.repoTokenConcentrationLimit }}
          NEW_REQUIRED_RESERVE_RATIO: ${{ github.event.inputs.requiredReserveRatio }}
          ADMIN_ADDRESS: ${{ vars.ADMIN_ADDRESS }}
          DEVOPS_ADDRESS: ${{ vars.DEVOPS_ADDRESS }}
          STRATEGY_META: ${{ github.event.inputs.strategyMeta }}
          PROFIT_MAX_UNLOCK_TIME: ${{ vars.PROFIT_MAX_UNLOCK_TIME }}
          STRATEGY_MANAGEMENT_ADDRESS: ${{ github.event.inputs.strategyManagementAddress }}
          KEEPER_ADDRESS: ${{ vars.KEEPER }}
          FEE_RECIPIENT: ${{ github.event.inputs.feeRecipient }}
          COLLATERAL_TOKEN_ADDRESSES: ${{ github.event.inputs.collateralTokens }}
          MIN_COLLATERAL_RATIOS: ${{ github.event.inputs.minCollateralRatios }}
          GOVERNOR_ROLE_ADDRESS: ${{ vars.GOVERNANCE_FACTORY }}
          SEPOLIA_RPC_URL:  ${{ secrets.RPC_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          
          # TODO(andrew please confirm): I don't think these are used for this workflow
          # GOVERNOR_DEPLOYER_KEY: ${{ secrets.GOVERNANCE_DEPLOYER_KEY }}
          # ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          # IS_TEST: true
  
